USE movielista;

-- ----------------------------------- TITLES

INSERT INTO titles -- 100
VALUES
	('1', 'Greenfelder Inc', 'Kovacek-Gleason'),
	('2', 'Waelchi, Reichel and Haley', 'Botsford, Howe and Klocko'),
	('3', 'Roob, Dibbert and Ebert', ''),
	('4', 'Mertz, Durgan and Heaney', 'Ondricka, Farrell and Christiansen'),
	('5', 'Wisozk Ltd', 'Boyle-Armstrong'),
	('6', 'Stiedemann, Bernier and Ullrich', 'Wisozk, Haag and Schuster'),
	('7', 'Beer-Cruickshank', ''),
	('8', 'O\'Hara-Ziemann', ''),
	('9', 'Barton, Weissnat and Ryan', 'Bergstrom PLC'),
	('10', 'Cassin, Dickinson and Farrell', ''),
	('11', 'Feil-Greenholt', 'Rutherford LLC'),
	('12', 'Schoen LLC', 'Macejkovic, Buckridge and Konopelski'),
	('13', 'Lueilwitz, Kuhlman and Bauch', 'Pagac, Ruecker and Balistreri'),
	('14', 'Cummerata, Renner and Hermiston', ''),
	('15', 'Rempel-Howell', ''),
	('16', 'Padberg-Windler', ''),
	('17', 'Stracke, Roberts and O\'Conner', ''),
	('18', 'Klocko, Hamill and Gorczany', 'Watsica-Wiegand'),
	('19', 'Rutherford Inc', 'McClure, Kuhic and Klocko'),
	('20', 'Dickinson, Kozey and Ryan', ''),
	('21', 'White, Kunde and Thiel', 'O\'Conner and Sons'),
	('22', 'Blanda, Mueller and Lockman', ''),
	('23', 'Mueller, Hyatt and Grady', ''),
	('24', 'Kihn-Waters', 'Williamson-Conroy'),
	('25', 'Gaylord, Daniel and Becker', ''),
	('26', 'Goldner Group', ''),
	('27', 'O\'Keefe, Littel and Cassin', 'Hilll PLC'),
	('28', 'Jacobs, Waelchi and West', ''),
	('29', 'Daniel-Funk', 'Runte-Abshire'),
	('30', 'Blanda Inc', 'Keebler PLC'),
	('31', 'Cremin LLC', ''),
	('32', 'Brakus-Hand', ''),
	('33', 'Blanda-Hane', 'Schmidt, Kerluke and Hahn'),
	('34', 'Smith, Gerlach and Treutel', 'Bashirian-Barton'),
	('35', 'Bahringer-Pacocha', ''),
	('36', 'Gulgowski-Lindgren', ''),
	('37', 'Wilderman LLC', ''),
	('38', 'Kozey, Walter and Cremin', ''),
	('39', 'Howe LLC', 'Harvey, Krajcik and Carroll'),
	('40', 'Stamm Group', 'Boyle Group'),
	('41', 'Stokes-Beier', 'Lindgren-Nienow'),
	('42', 'Robel, Mayer and Jast', ''),
	('43', 'Romaguera, Mann and Keeling', 'Swaniawski-Corkery'),
	('44', 'Leuschke, Kertzmann and Schoen', ''),
	('45', 'Stokes-Kovacek', ''),
	('46', 'Cormier, Kiehn and Rolfson', 'Okuneva, Rosenbaum and Spinka'),
	('47', 'Hyatt Inc', 'Dicki-West'),
	('48', 'Goodwin Ltd', 'Wyman, Leffler and Block'),
	('49', 'Muller Inc', ''),
	('50', 'Nikolaus, Boehm and Littel', ''),
	('51', 'Christiansen Inc', 'Ondricka PLC'),
	('52', 'Eichmann-Gulgowski', ''),
	('53', 'Maggio and Sons', ''),
	('54', 'Schamberger Group', ''),
	('55', 'Weissnat PLC', 'Cormier-Stracke'),
	('56', 'Grady LLC', 'Schroeder-Hills'),
	('57', 'Stoltenberg-Witting', ''),
	('58', 'Heaney and Sons', ''),
	('59', 'Wolf-Buckridge', ''),
	('60', 'Schinner, Kilback and Gislason', ''),
	('61', 'Champlin-Walter', 'Cormier-Schuppe'),
	('62', 'Feest-Parisian', 'Swaniawski, Smith and Blick'),
	('63', 'Veum, Klein and Mayer', ''),
	('64', 'Green Ltd', ''),
	('65', 'Hane, Hagenes and Thiel', ''),
	('66', 'Beahan, Predovic and Grady', 'Parker-O\'Hara'),
	('67', 'Williamson Group', ''),
	('68', 'Welch-Schulist', 'Harvey, Cronin and Boyer'),
	('69', 'Herman, Pollich and Weber', ''),
	('70', 'Cole-Rosenbaum', ''),
	('71', 'Armstrong-Pollich', 'Medhurst, Kovacek and Rolfson'),
	('72', 'Kemmer Group', 'Lowe, Nikolaus and Rempel'),
	('73', 'Smith and Sons', ''),
	('74', 'Breitenberg Group', 'Gulgowski-McDermott'),
	('75', 'Dach-Jacobi', ''),
	('76', 'Wisoky-Bins', 'Stehr-Kirlin'),
	('77', 'Lakin-Lang', ''),
	('78', 'Wiza, Rowe and Hodkiewicz', ''),
	('79', 'Mitchell Group', 'Tromp, Quitzon and Barrows'),
	('80', 'Cormier, Ebert and Witting', 'Hand-Bednar'),
	('81', 'Franecki Ltd', 'Wilkinson-Stiedemann'),
	('82', 'Bergnaum PLC', ''),
	('83', 'Walsh Group', ''),
	('84', 'Emard-Towne', ''),
	('85', 'Lehner LLC', 'O\'Kon Ltd'),
	('86', 'Torp LLC', ''),
	('87', 'Lubowitz-Kohler', 'Harber, Berge and Bosco'),
	('88', 'Crist-O\'Reilly', ''),
	('89', 'Ryan, Bartell and Stehr', 'Homenick-Walsh'),
	('90', 'Hermann-Stiedemann', 'Carroll, Marquardt and Heidenreich'),
	('91', 'Schaden and Sons', ''),
	('92', 'Murray Group', 'Hettinger, Schimmel and Schaefer'),
	('93', 'Padberg Group', ''),
	('94', 'Mertz-Lebsack', ''),
	('95', 'Wolff, Kuhlman and Bahringer', ''),
	('96', 'White and Sons', 'McKenzie-Wintheiser'),
	('97', 'Dicki, Wehner and Stokes', ''),
	('98', 'Kemmer-Goyette', ''),
	('99', 'Stokes, Hoppe and Pagac', ''),
	('100', 'Labadie-Cremin', 'Weissnat LLC');

INSERT INTO title_info(title_id, title_type_id, poster, tagline, synopsis, release_date, rars)
VALUES
	('1', '4', '121', 'Expanded secondary product',
	 'Alice, \'when one wasn\'t always growing larger and smaller, and being so many lessons to learn! Oh, I shouldn\'t want YOURS: I don\'t like them!\' When the procession moved on, three of the day; and this was not even room for this, and she thought to herself \'That\'s quite enough--I hope I shan\'t grow any more--As it is, I suppose?\' said Alice. \'Call.',
	 '2000-05-19', 'NR'),
	('2', '6', '131', 'Multi-channelled bottom-line complexity',
	 'I to do it! Oh dear! I\'d nearly forgotten to ask.\' \'It turned into a tree. \'Did you say it.\' \'That\'s nothing to what I should be like then?\' And she began again: \'Ou est ma chatte?\' which was full of soup. \'There\'s certainly too much overcome to do next, when suddenly a White Rabbit read:-- \'They told me you had been would have appeared to them.',
	 '2002-04-13', '18+'),
	('3', '5', '46', 'Enhanced regional concept',
	 'As soon as it turned round and swam slowly back again, and all must have imitated somebody else\'s hand,\' said the Gryphon replied very solemnly. Alice was not here before,\' said Alice,) and round Alice, every now and then another confusion of voices--\'Hold up his head--Brandy now--Don\'t choke him--How was it, old fellow? What happened to you?.',
	 '2016-11-07', '6+'),
	('4', '2', '110', 'Fully-configurable fault-tolerant flexibility',
	 'I shan\'t! YOU do it!--That I won\'t, then!--Bill\'s to go nearer till she was playing against herself, for this curious child was very fond of pretending to be seen--everything seemed to Alice a good thing!\' she said this, she was quite a long time with the day and night! You see the earth takes twenty-four hours to turn into a pig, my dear,\' said.',
	 '2006-08-15', '18+'),
	('5', '5', '73', 'Fully-configurable real-time knowledgeuser',
	 'Hatter. \'You might just as she could guess, she was going to remark myself.\' \'Have you guessed the riddle yet?\' the Hatter with a bound into the loveliest garden you ever saw. How she longed to get in at once.\' And in she went. Once more she found that it had gone. \'Well! I\'ve often seen them at dinn--\' she checked herself hastily. \'I thought you.',
	 '1985-10-18', '16+'),
	('6', '4', '8', 'Diverse background emulation',
	 'Alice, surprised at her own courage. \'It\'s no business of MINE.\' The Queen smiled and passed on. \'Who ARE you doing out here? Run home this moment, and fetch me a good character, But said I didn\'t!\' interrupted Alice. \'You did,\' said the Caterpillar contemptuously. \'Who are YOU?\' said the Mock Turtle repeated thoughtfully. \'I should like to be.',
	 '1994-04-27', '18+'),
	('7', '5', '120', 'Self-enabling bandwidth-monitored forecast',
	 'She said the Gryphon. \'--you advance twice--\' \'Each with a melancholy tone: \'it doesn\'t seem to see that queer little toss of her voice, and see after some executions I have none, Why, I wouldn\'t say anything about it, so she took up the little golden key, and when she was talking. \'How CAN I have dropped them, I wonder?\' As she said to the King,.',
	 '2008-03-21', '18+'),
	('8', '3', '126', 'Diverse background application',
	 'King, and the blades of grass, but she saw maps and pictures hung upon pegs. She took down a large dish of tarts upon it: they looked so grave that she had peeped into the sky. Alice went on to himself as he spoke. \'A cat may look at it!\' This speech caused a remarkable sensation among the trees, a little ledge of rock, and, as a drawing of a.',
	 '2005-05-27', '6+'),
	('9', '6', '150', 'De-engineered non-volatile flexibility',
	 'Gryphon; and then the puppy began a series of short charges at the Cat\'s head began fading away the moment he was going to give the hedgehog had unrolled itself, and began bowing to the general conclusion, that wherever you go on? It\'s by far the most confusing thing I know. Silence all round, if you were or might have been a RED rose-tree, and.',
	 '2006-05-20', '0+'),
	('10', '4', '91', 'Extended optimizing securedline',
	 'Alice, in a low, trembling voice. \'There\'s more evidence to come down the chimney, and said to herself, \'whenever I eat one of the words did not venture to say it over) \'--yes, that\'s about the games now.\' CHAPTER X. The Lobster Quadrille The Mock Turtle went on, \'and most things twinkled after that--only the March Hare had just begun to repeat.',
	 '1997-07-19', '6+'),
	('11', '5', '12', 'Automated bi-directional implementation',
	 'Alice thought over all the while, and fighting for the hot day made her next remark. \'Then the eleventh day must have a trial: For really this morning I\'ve nothing to do: once or twice, and shook itself. Then it got down off the subjects on his slate with one eye; but to open them again, and Alice looked very anxiously into her head. \'If I eat or.',
	 '1978-12-17', '16+'),
	('12', '2', '145', 'Synergistic foreground hub',
	 'I\'m quite tired of this. I vote the young Crab, a little feeble, squeaking voice, (\'That\'s Bill,\' thought Alice,) \'Well, I can\'t get out at all a pity. I said \"What for?\"\' \'She boxed the Queen\'s hedgehog just now, only it ran away when it grunted again, so she took courage, and went in. The door led right into a pig,\' Alice quietly said, just as.',
	 '2002-09-27', 'NR'),
	('13', '1', '123', 'Cloned discrete help-desk',
	 'Tell us all about for a minute or two to think about it, you know.\' \'I don\'t think it\'s at all fairly,\' Alice began, in a hurry: a large fan in the pool a little sharp bark just over her head through the door, and tried to get out again. That\'s all.\' \'Thank you,\' said the Gryphon: and Alice thought to herself. \'I dare say there may be different,\'.',
	 '2018-07-17', '18+'),
	('14', '1', '146', 'Automated client-driven time-frame',
	 'The jury all wrote down on one side, to look about her and to hear his history. I must have been a holiday?\' \'Of course you know the song, she kept on good terms with him, he\'d do almost anything you liked with the birds and animals that had made her draw back in a hurry: a large fan in the distance. \'Come on!\' cried the Mouse, turning to Alice:.',
	 '1979-04-02', 'NR'),
	('15', '5', '119', 'Quality-focused actuating adapter',
	 'That WILL be a walrus or hippopotamus, but then she remembered that she could not help bursting out laughing: and when she looked down at once, in a wondering tone. \'Why, what are YOUR shoes done with?\' said the Hatter. Alice felt that it might injure the brain; But, now that I\'m perfectly sure I don\'t like them raw.\' \'Well, be off, and found.',
	 '1999-01-27', '0+'),
	('16', '4', '1', 'Robust system-worthy hardware',
	 'VERY wide, but she knew that it was neither more nor less than a pig, my dear,\' said Alice, who was beginning to end,\' said the Caterpillar. Alice said to herself; \'the March Hare will be When they take us up and throw us, with the bones and the sound of many footsteps, and Alice was very likely to eat some of the guinea-pigs cheered, and was.',
	 '2002-04-12', '12+'),
	('17', '2', '94', 'Team-oriented contextually-based structure',
	 'Lory, with a T!\' said the Mouse. \'--I proceed. \"Edwin and Morcar, the earls of Mercia and Northumbria--\"\' \'Ugh!\' said the Pigeon went on, taking first one side and up the fan she was to get out at the sudden change, but she could not help bursting out laughing: and when Alice had no idea what Latitude was, or Longitude I\'ve got to the law, And.',
	 '2014-04-18', '6+'),
	('18', '5', '88', 'Expanded multi-state groupware',
	 'Alice\'s first thought was that you couldn\'t cut off a little different. But if I\'m not used to say \'Drink me,\' but the Mouse to Alice a little timidly: \'but it\'s no use in waiting by the way I ought to tell you--all I know is, it would be worth the trouble of getting up and to stand on their hands and feet at once, with a whiting. Now you know.\'.',
	 '2005-05-13', '12+'),
	('19', '4', '51', 'Profound responsive capability',
	 'As there seemed to listen, the whole place around her became alive with the words all coming different, and then sat upon it.) \'I\'m glad they don\'t seem to encourage the witness at all: he kept shifting from one foot to the confused clamour of the way out of sight; and an Eaglet, and several other curious creatures. Alice led the way, was the.',
	 '1989-04-05', '18+'),
	('20', '1', '123', 'Enterprise-wide stable systemengine',
	 'Majesty,\' he began. \'You\'re a very good height indeed!\' said the Dormouse, not choosing to notice this last remark. \'Of course it is,\' said the Hatter: \'let\'s all move one place on.\' He moved on as he came, \'Oh! the Duchess, as she did not quite know what you would seem to put his mouth close to her lips. \'I know what you had been found and.',
	 '2013-03-31', '12+'),
	('21', '5', '136', 'Horizontal directional ability',
	 'Fish-Footman was gone, and the baby was howling so much at first, perhaps,\' said the Mock Turtle. Alice was just going to be, from one end to the end of the doors of the e--e--evening, Beautiful, beautiful Soup!\' CHAPTER XI. Who Stole the Tarts? The King and the Mock Turtle sighed deeply, and began, in a pleased tone. \'Pray don\'t trouble yourself.',
	 '1997-03-24', '18+'),
	('22', '1', '45', 'Persevering multimedia artificialintelligence',
	 'The moment Alice felt a very hopeful tone though), \'I won\'t have any rules in particular; at least, if there were no arches left, and all sorts of things--I can\'t remember things as I get it home?\' when it grunted again, and looking anxiously about her. \'Oh, do let me help to undo it!\' \'I shall sit here,\' he said, turning to the jury. \'Not yet,.',
	 '1982-11-17', '6+'),
	('23', '2', '135', 'Enterprise-wide system-worthy GraphicInterface',
	 'Queen. \'Can you play croquet?\' The soldiers were silent, and looked at the proposal. \'Then the Dormouse again, so violently, that she hardly knew what she was saying, and the Hatter added as an explanation; \'I\'ve none of my life.\' \'You are not the right way of keeping up the conversation a little. \'\'Tis so,\' said the Pigeon in a rather offended.',
	 '1985-01-13', '12+'),
	('24', '3', '63', 'Organized contextually-based projection',
	 'So she set off at once without waiting for the pool of tears which she found a little bit, and said anxiously to herself, \'it would be QUITE as much use in crying like that!\' By this time it all came different!\' the Mock Turtle yawned and shut his note-book hastily. \'Consider your verdict,\' the King exclaimed, turning to the Caterpillar, just as.',
	 '2013-06-29', '18+'),
	('25', '5', '91', 'Automated tangible workforce',
	 'Dormouse, who seemed too much of a candle is like after the birds! Why, she\'ll eat a little different. But if I\'m Mabel, I\'ll stay down here till I\'m somebody else\"--but, oh dear!\' cried Alice again, for really I\'m quite tired and out of the players to be sure! However, everything is queer to-day.\' Just then she remembered trying to explain it is.',
	 '2005-12-21', '16+'),
	('26', '5', '49', 'Ergonomic optimal policy',
	 'Alice asked in a very little way forwards each time and a Dodo, a Lory and an old Turtle--we used to read fairy-tales, I fancied that kind of rule, \'and vinegar that makes them sour--and camomile that makes people hot-tempered,\' she went on, \'you see, a dog growls when it\'s pleased. Now I growl when I\'m pleased, and wag my tail when it\'s pleased..',
	 '1976-09-01', '18+'),
	('27', '6', '34', 'Phased dedicated synergy',
	 'Why, I wouldn\'t be in before the trial\'s begun.\' \'They\'re putting down their names,\' the Gryphon added \'Come, let\'s try the effect: the next moment she appeared; but she had been all the time they had at the beginning,\' the King say in a soothing tone: \'don\'t be angry about it. And yet I don\'t want to be?\' it asked. \'Oh, I\'m not Ada,\' she said,.',
	 '2012-07-21', '16+'),
	('28', '3', '15', 'Stand-alone web-enabled intranet',
	 'March Hare interrupted, yawning. \'I\'m getting tired of being upset, and their slates and pencils had been for some time after the rest waited in silence. At last the Caterpillar took the watch and looked at her rather inquisitively, and seemed to listen, the whole pack rose up into the teapot. \'At any rate a book written about me, that there was.',
	 '2007-07-15', '0+'),
	('29', '3', '87', 'Polarised user-facing access',
	 'And oh, I wish you wouldn\'t mind,\' said Alice: \'allow me to him: She gave me a pair of the way I ought to have no sort of a water-well,\' said the Queen. \'Sentence first--verdict afterwards.\' \'Stuff and nonsense!\' said Alice indignantly, and she tried hard to whistle to it; but she had forgotten the words.\' So they had at the Lizard as she went.',
	 '1988-02-14', '12+'),
	('30', '3', '39', 'Advanced zerodefect archive',
	 'Mock Turtle sighed deeply, and began, in a deep voice, \'are done with a lobster as a lark, And will talk in contemptuous tones of her own mind (as well as I used--and I don\'t know where Dinn may be,\' said the Cat said, waving its tail when it\'s angry, and wags its tail about in the last time she heard a little bit, and said to the Dormouse, who.',
	 '2017-09-18', '6+'),
	('31', '5', '39', 'Profit-focused homogeneous GraphicalUserInterface',
	 'On various pretexts they all crowded together at one and then unrolled the parchment scroll, and read out from his book, \'Rule Forty-two. ALL PERSONS MORE THAN A MILE HIGH TO LEAVE THE COURT.\' Everybody looked at Two. Two began in a very good advice, (though she very seldom followed it), and handed them round as prizes. There was nothing so VERY.',
	 '1980-10-04', '6+'),
	('32', '6', '45', 'Re-contextualized 3rdgeneration installation',
	 'Dodo, pointing to the seaside once in a sorrowful tone; \'at least there\'s no use in crying like that!\' He got behind Alice as she spoke; \'either you or your head must be Mabel after all, and I could shut up like a steam-engine when she noticed a curious feeling!\' said Alice; \'I daresay it\'s a set of verses.\' \'Are they in the middle, being held up.',
	 '2008-07-09', '16+'),
	('33', '3', '144', 'Pre-emptive demand-driven matrices',
	 'I suppose I ought to be executed for having missed their turns, and she sat down and cried. \'Come, there\'s half my plan done now! How puzzling all these changes are! I\'m never sure what I\'m going to dive in among the branches, and every now and then a great interest in questions of eating and drinking. \'They lived on treacle,\' said the Footman,.',
	 '2016-01-30', '18+'),
	('34', '5', '96', 'Monitored national capacity',
	 'Alice to find her in an undertone to the general conclusion, that wherever you go to on the end of the baby, the shriek of the crowd below, and there was Mystery,\' the Mock Turtle said: \'advance twice, set to work, and very neatly and simply arranged; the only difficulty was, that her neck from being run over; and the fan, and skurried away into.',
	 '1971-01-10', '0+'),
	('35', '4', '24', 'Diverse local extranet',
	 'Alice had been looking at the March Hare: she thought it would feel very uneasy: to be sure; but I THINK I can say.\' This was not going to do this, so that her neck would bend about easily in any direction, like a stalk out of his teacup instead of onions.\' Seven flung down his brush, and had just upset the milk-jug into his plate. Alice did not.',
	 '2012-12-23', '0+'),
	('36', '1', '117', 'Grass-roots zeroadministration neural-net',
	 'Gryphon. \'Well, I should say \"With what porpoise?\"\' \'Don\'t you mean \"purpose\"?\' said Alice. \'Why?\' \'IT DOES THE BOOTS AND SHOES.\' the Gryphon answered, very nearly in the last few minutes she heard a little of her skirt, upsetting all the other side will make you a present of everything I\'ve said as yet.\' \'A cheap sort of way, \'Do cats eat bats,.',
	 '2006-12-31', '12+'),
	('37', '4', '74', 'Polarised composite database',
	 'RETURNED FROM HIM TO YOU,\"\' said Alice. \'Did you speak?\' \'Not I!\' he replied. \'We quarrelled last March--just before HE went mad, you know--\' (pointing with his head!\' she said, \'for her hair goes in such a wretched height to rest herself, and began an account of the sense, and the White Rabbit, \'and that\'s why. Pig!\' She said it to be lost, as.',
	 '2008-01-16', 'NR'),
	('38', '6', '139', 'Multi-lateral user-facing paradigm',
	 'King said to Alice; and Alice called after her. \'I\'ve something important to say!\' This sounded promising, certainly: Alice turned and came flying down upon their faces, so that her neck kept getting entangled among the people near the entrance of the gloves, and she soon made out that the Mouse had changed his mind, and was a little bit, and.',
	 '2013-01-31', '18+'),
	('39', '3', '145', 'Down-sized systematic adapter',
	 'Alice was not going to leave the room, when her eye fell upon a little shriek and a large pool all round the hall, but they all crowded round it, panting, and asking, \'But who is Dinah, if I fell off the subjects on his flappers, \'--Mystery, ancient and modern, with Seaography: then Drawling--the Drawling-master was an old conger-eel, that used.',
	 '1971-10-30', '16+'),
	('40', '6', '96', 'Re-engineered responsive internetsolution',
	 'Ann! Mary Ann!\' said the King. \'It began with the glass table as before, \'It\'s all about for them, and it\'ll sit up and rubbed its eyes: then it watched the White Rabbit, jumping up and walking away. \'You insult me by talking such nonsense!\' \'I didn\'t mean it!\' pleaded poor Alice in a hurried nervous manner, smiling at everything about her, to.',
	 '1990-08-22', '0+'),
	('41', '3', '69', 'Function-based system-worthy website',
	 'Mock Turtle said with a kind of sob, \'I\'ve tried every way, and nothing seems to grin, How neatly spread his claws, And welcome little fishes in With gently smiling jaws!\' \'I\'m sure those are not attending!\' said the Queen. \'Sentence first--verdict afterwards.\' \'Stuff and nonsense!\' said Alice sharply, for she was losing her temper. \'Are you.',
	 '1986-03-23', '18+'),
	('42', '5', '128', 'Open-architected multimedia throughput',
	 'Mock Turtle sighed deeply, and drew the back of one flapper across his eyes. He looked anxiously over his shoulder as he fumbled over the list, feeling very glad to do it.\' (And, as you are; secondly, because they\'re making such VERY short remarks, and she was walking hand in her life, and had just upset the milk-jug into his plate. Alice did not.',
	 '1972-12-29', '16+'),
	('43', '3', '18', 'Future-proofed discrete functionalities',
	 'Alice was more hopeless than ever: she sat on, with closed eyes, and feebly stretching out one paw, trying to touch her. \'Poor little thing!\' It did so indeed, and much sooner than she had not noticed before, and he called the Queen, in a bit.\' \'Perhaps it doesn\'t matter much,\' thought Alice, \'or perhaps they won\'t walk the way the people that.',
	 '1974-09-25', 'NR'),
	('44', '3', '3', 'Enterprise-wide system-worthy artificialintelligence',
	 'When they take us up and bawled out, \"He\'s murdering the time! Off with his head!\' she said, \'and see whether it\'s marked \"poison\" or not\'; for she was holding, and she thought it had some kind of sob, \'I\'ve tried every way, and then another confusion of voices--\'Hold up his head--Brandy now--Don\'t choke him--How was it, old fellow? What happened.',
	 '1974-05-07', '6+'),
	('45', '1', '102', 'Organized multi-state array',
	 'NOT, being made entirely of cardboard.) \'All right, so far,\' said the Rabbit was still in sight, and no more of it now in sight, hurrying down it. There was exactly the right height to be.\' \'It is a raven like a writing-desk?\' \'Come, we shall have to whisper a hint to Time, and round the court was a large kitchen, which was sitting on the.',
	 '1975-08-12', '6+'),
	('46', '2', '56', 'Team-oriented tertiary focusgroup',
	 'Alice, \'it would be so kind,\' Alice replied, rather shyly, \'I--I hardly know, sir, just at first, the two creatures got so much frightened to say whether the blows hurt it or not. \'Oh, PLEASE mind what you\'re at!\" You know the meaning of it in her hand, watching the setting sun, and thinking of little cartwheels, and the other guinea-pig cheered,.',
	 '1992-04-04', '12+'),
	('47', '6', '139', 'Focused transitional securedline',
	 'I was a little of the e--e--evening, Beautiful, beautiful Soup! \'Beautiful Soup! Who cares for you?\' said Alice, swallowing down her flamingo, and began an account of the court and got behind him, and very angrily. \'A knot!\' said Alice, surprised at her feet as the doubled-up soldiers were always getting up and throw us, with the Dormouse. \'Don\'t.',
	 '1999-12-22', '18+'),
	('48', '6', '11', 'Quality-focused real-time internetsolution',
	 'Alice, who was trembling down to them, and the moon, and memory, and muchness--you know you say things are worse than ever,\' thought the whole thing very absurd, but they were nowhere to be sure! However, everything is to-day! And yesterday things went on saying to herself how she would get up and went on in the sea, \'and in that soup!\' Alice.',
	 '1978-05-24', '16+'),
	('49', '4', '84', 'Configurable didactic policy',
	 'Where CAN I have ordered\'; and she grew no larger: still it was certainly not becoming. \'And that\'s the queerest thing about it.\' (The jury all looked puzzled.) \'He must have been that,\' said the cook. The King turned pale, and shut his note-book hastily. \'Consider your verdict,\' he said in a tone of great surprise. \'Of course they were\', said.',
	 '2003-06-08', '18+'),
	('50', '3', '33', 'De-engineered holistic product',
	 'With gently smiling jaws!\' \'I\'m sure I\'m not the right size, that it was labelled \'ORANGE MARMALADE\', but to her full size by this time.) \'You\'re nothing but a pack of cards: the Knave \'Turn them over!\' The Knave did so, and were resting in the world go round!\"\' \'Somebody said,\' Alice whispered, \'that it\'s done by everybody minding their own.',
	 '2009-07-02', '16+'),
	('51', '1', '51', 'Ameliorated methodical forecast',
	 'Shakespeare, in the common way. So she swallowed one of the miserable Mock Turtle. \'Seals, turtles, salmon, and so on; then, when you\'ve cleared all the time he had taken advantage of the Lizard\'s slate-pencil, and the shrill voice of the baby?\' said the Caterpillar. This was such a thing. After a time she had known them all her life. Indeed, she.',
	 '1971-03-25', '6+'),
	('52', '4', '36', 'Total content-based encryption',
	 'May it won\'t be raving mad after all! I almost wish I hadn\'t gone down that rabbit-hole--and yet--and yet--it\'s rather curious, you know, with oh, such long curly brown hair! And it\'ll fetch things when you come to the baby, the shriek of the other side, the puppy began a series of short charges at the frontispiece if you like!\' the Duchess to.',
	 '2013-08-01', '18+'),
	('53', '1', '72', 'Extended client-server instructionset',
	 'Mystery,\' the Mock Turtle. \'Very much indeed,\' said Alice. The poor little thing sobbed again (or grunted, it was quite pale (with passion, Alice thought), and it said nothing. \'When we were little,\' the Mock Turtle replied in a melancholy air, and, after glaring at her as she passed; it was very fond of beheading people here; the great puzzle!\'.',
	 '1990-07-13', '12+'),
	('54', '4', '108', 'Total contextually-based protocol',
	 'Alice ventured to say. \'What is it?\' he said, turning to Alice with one finger; and the moon, and memory, and muchness--you know you say things are worse than ever,\' thought the poor little thing sat down and looked along the passage into the garden with one of them were animals, and some \'unimportant.\' Alice could not even room for YOU, and no.',
	 '1988-08-26', '6+'),
	('55', '3', '77', 'Re-contextualized stable migration',
	 'I begin, please your Majesty,\' said Alice in a moment: she looked down at them, and he went on, looking anxiously about as it left no mark on the look-out for serpents night and day! Why, I haven\'t been invited yet.\' \'You\'ll see me there,\' said the Caterpillar. \'Well, I\'ve tried to say than his first remark, \'It was a good opportunity for making.',
	 '1973-09-09', '6+'),
	('56', '6', '32', 'Synergized human-resource synergy',
	 'Mock Turtle, \'but if they do, why then they\'re a kind of authority over Alice. \'Stand up and bawled out, \"He\'s murdering the time! Off with his head!\"\' \'How dreadfully savage!\' exclaimed Alice. \'That\'s the first to break the silence. \'What day of the room. The cook threw a frying-pan after her as she went on, yawning and rubbing its eyes, \'Of.',
	 '2008-01-27', '6+'),
	('57', '2', '121', 'Reactive high-level approach',
	 'I was, I shouldn\'t want YOURS: I don\'t care which happens!\' She ate a little house in it about four feet high. \'Whoever lives there,\' thought Alice, \'to pretend to be otherwise.\"\' \'I think you could see this, as she could, for her neck kept getting entangled among the leaves, which she found it made Alice quite jumped; but she did so, and giving.',
	 '1979-09-14', '0+'),
	('58', '4', '54', 'Ameliorated 4thgeneration attitude',
	 'And yet I don\'t put my arm round your waist,\' the Duchess said after a few minutes that she could not think of nothing else to do, so Alice went timidly up to the other players, and shouting \'Off with her friend. When she got to come before that!\' \'Call the first figure!\' said the Caterpillar took the place where it had finished this short.',
	 '2012-02-05', '6+'),
	('59', '6', '11', 'Universal real-time encryption',
	 'He sent them word I had to do it?\' \'In my youth,\' Father William replied to his son, \'I feared it might belong to one of the guinea-pigs cheered, and was going to be, from one foot up the fan she was near enough to look for her, and said, \'That\'s right, Five! Always lay the blame on others!\' \'YOU\'D better not do that again!\' which produced.',
	 '2016-01-08', '16+'),
	('60', '2', '3', 'Networked intangible productivity',
	 'King said, with a soldier on each side, and opened their eyes and mouths so VERY nearly at the door and found quite a conversation of it now in sight, hurrying down it. There was a dispute going on rather better now,\' she said, \'than waste it in a melancholy tone: \'it doesn\'t seem to have the experiment tried. \'Very true,\' said the Hatter, and.',
	 '1981-01-13', 'NR'),
	('61', '3', '145', 'Re-engineered 24/7 knowledgebase',
	 'Some of the jurymen. \'No, they\'re not,\' said the King. \'Nothing whatever,\' said Alice. \'I\'m glad they don\'t seem to dry me at home! Why, I haven\'t been invited yet.\' \'You\'ll see me there,\' said the Duchess. An invitation for the moment she appeared; but she added, to herself, as well as the Dormouse shall!\' they both cried. \'Wake up, Alice dear!\'.',
	 '2010-11-09', '12+'),
	('62', '6', '8', 'Multi-tiered impactful software',
	 'It sounded an excellent plan, no doubt, and very soon finished off the fire, stirring a large mushroom growing near her, about the twentieth time that day. \'A likely story indeed!\' said the King. \'Shan\'t,\' said the Hatter. He had been running half an hour or so there were no arches left, and all dripping wet, cross, and uncomfortable. The moment.',
	 '1991-07-29', '0+'),
	('63', '4', '127', 'Balanced impactful productivity',
	 'Hatter, \'you wouldn\'t talk about her repeating \'YOU ARE OLD, FATHER WILLIAM,\"\' said the last word two or three times over to the game, the Queen shouted at the place of the garden, and marked, with one of them even when they passed too close, and waving their forepaws to mark the time, while the Mouse was bristling all over, and she trembled till.',
	 '2012-02-22', '16+'),
	('64', '6', '74', 'Stand-alone modular complexity',
	 'Dormouse say?\' one of the jurymen. \'No, they\'re not,\' said the White Rabbit; \'in fact, there\'s nothing written on the top of her voice. Nobody moved. \'Who cares for fish, Game, or any other dish? Who would not allow without knowing how old it was, and, as a partner!\' cried the Gryphon, \'she wants for to know your history, you know,\' the Hatter.',
	 '2005-10-13', '16+'),
	('65', '3', '92', 'Centralized hybrid attitude',
	 'The Fish-Footman began by taking the little creature down, and was going to begin with.\' \'A barrowful of WHAT?\' thought Alice to herself. At this moment the King, going up to them she heard something like this:-- \'Fury said to the little crocodile Improve his shining tail, And pour the waters of the fact. \'I keep them to sell,\' the Hatter said,.',
	 '2002-10-05', '18+'),
	('66', '4', '41', 'Public-key executive software',
	 'Majesty?\' he asked. \'Begin at the end of his head. But at any rate, there\'s no name signed at the cook, and a piece of evidence we\'ve heard yet,\' said the King. \'Nothing whatever,\' said Alice. \'Well, then,\' the Gryphon only answered \'Come on!\' cried the Mouse, getting up and throw us, with the grin, which remained some time with one of them even.',
	 '2013-01-17', '12+'),
	('67', '2', '9', 'Enterprise-wide demand-driven artificialintelligence',
	 'Duchess: you\'d better leave off,\' said the March Hare. \'Yes, please do!\' pleaded Alice. \'And where HAVE my shoulders got to? And oh, I wish you would seem to come once a week: HE taught us Drawling, Stretching, and Fainting in Coils.\' \'What was that?\' inquired Alice. \'Reeling and Writhing, of course, I meant,\' the King put on his knee, and the.',
	 '1987-10-12', 'NR'),
	('68', '5', '126', 'Realigned maximized firmware',
	 'If they had a head could be beheaded, and that you weren\'t to talk to.\' \'How are you thinking of?\' \'I beg your pardon,\' said Alice sharply, for she was now about two feet high: even then she remembered the number of executions the Queen of Hearts were seated on their slates, and then all the things get used up.\' \'But what happens when one eats.',
	 '1992-11-04', '18+'),
	('69', '3', '116', 'Universal tangible time-frame',
	 'However, at last in the middle. Alice kept her eyes anxiously fixed on it, and talking over its head. \'Very uncomfortable for the White Rabbit, trotting slowly back again, and did not look at the bottom of the Queen in a melancholy tone. \'Nobody seems to be executed for having cheated herself in a great hurry. An enormous puppy was looking up.',
	 '1999-01-18', '0+'),
	('70', '1', '97', 'Reactive modular flexibility',
	 'Alice. \'Nothing WHATEVER?\' persisted the King. The White Rabbit cried out, \'Silence in the house, and found herself falling down a very good advice, (though she very soon finished it off. \'If everybody minded their own business!\' \'Ah, well! It means much the same year for such dainties would not stoop? Soup of the lefthand bit. * * CHAPTER II..',
	 '1977-02-17', '0+'),
	('71', '5', '48', 'Diverse system-worthy info-mediaries',
	 'Alice, always ready to play croquet with the bread-knife.\' The March Hare will be much the same thing as \"I eat what I was thinking I should like to try the experiment?\' \'HE might bite,\' Alice cautiously replied, not feeling at all anxious to have lessons to learn! Oh, I shouldn\'t want YOURS: I don\'t remember where.\' \'Well, it must make me.',
	 '1997-05-02', '0+'),
	('72', '6', '101', 'Multi-layered global artificialintelligence',
	 'Hatter began, in a great thistle, to keep herself from being broken. She hastily put down her flamingo, and began singing in its sleep \'Twinkle, twinkle, twinkle, twinkle--\' and went on just as if a fish came to ME, and told me you had been looking at the top of the what?\' said the Caterpillar. \'Well, I\'ve tried hedges,\' the Pigeon the.',
	 '2019-09-16', 'NR'),
	('73', '2', '150', 'Enterprise-wide 5thgeneration knowledgeuser',
	 'It means much the most important piece of bread-and-butter in the middle, being held up by two guinea-pigs, who were lying on their slates, and she dropped it hastily, just in time to see if she could remember about ravens and writing-desks, which wasn\'t much. The Hatter opened his eyes very wide on hearing this; but all he SAID was, \'Why is a.',
	 '2005-03-02', '12+'),
	('74', '2', '18', 'Front-line even-keeled model',
	 'Mock Turtle with a little shaking among the trees, a little pattering of feet in a low, weak voice. \'Now, I give you fair warning,\' shouted the Queen. \'You make me larger, it must be off, then!\' said the King: \'leave out that the best plan.\' It sounded an excellent opportunity for croqueting one of the treat. When the sands are all dry, he is gay.',
	 '2015-07-31', 'NR'),
	('75', '2', '87', 'User-centric optimal archive',
	 'Edwin and Morcar, the earls of Mercia and Northumbria--\"\' \'Ugh!\' said the Cat. \'Do you take me for asking! No, it\'ll never do to hold it. As soon as she could, and waited till the eyes appeared, and then the different branches of Arithmetic--Ambition, Distraction, Uglification, and Derision.\' \'I never heard of one,\' said Alice, in a very short.',
	 '2005-04-24', '18+'),
	('76', '6', '12', 'Visionary grid-enabled frame',
	 'Duchess, the Duchess! Oh! won\'t she be savage if I\'ve been changed in the sea, \'and in that ridiculous fashion.\' And he got up very sulkily and crossed over to the puppy; whereupon the puppy jumped into the darkness as hard as she was now the right size, that it had entirely disappeared; so the King said gravely, \'and go on crying in this way!.',
	 '2009-03-27', '18+'),
	('77', '4', '5', 'Customer-focused interactive info-mediaries',
	 'Alice, \'it\'ll never do to ask: perhaps I shall remember it in her head, and she dropped it hastily, just in time to wash the things between whiles.\' \'Then you may nurse it a minute or two she walked on in the kitchen that did not like to be listening, so she went in without knocking, and hurried upstairs, in great disgust, and walked off; the.',
	 '1970-12-01', 'NR'),
	('78', '6', '133', 'Customizable foreground alliance',
	 'VERY nearly at the thought that it might tell her something worth hearing. For some minutes it puffed away without being seen, when she noticed that the cause of this sort of people live about here?\' \'In THAT direction,\' the Cat went on, very much to-night, I should understand that better,\' Alice said very politely, \'if I had our Dinah here, I.',
	 '2004-07-21', '12+'),
	('79', '3', '138', 'Polarised empowering contingency',
	 'Her chin was pressed so closely against her foot, that there was mouth enough for it now, I suppose, by being drowned in my life!\' Just as she spoke. Alice did not quite sure whether it was over at last: \'and I do it again and again.\' \'You are old,\' said the Mock Turtle, capering wildly about. \'Change lobsters again!\' yelled the Gryphon never.',
	 '2007-09-24', '16+'),
	('80', '5', '142', 'Profound zerodefect database',
	 'Mock Turtle with a deep voice, \'are done with blacking, I believe.\' \'Boots and shoes under the circumstances. There was a very humble tone, going down on one knee as he spoke, and then dipped suddenly down, so suddenly that Alice quite jumped; but she got up, and began by taking the little creature down, and was just in time to begin with; and.',
	 '1983-06-06', '16+'),
	('81', '1', '107', 'Reactive zerodefect intranet',
	 'Caterpillar seemed to be a person of authority among them, called out, \'First witness!\' The first witness was the White Rabbit read:-- \'They told me he was gone, and the three gardeners, but she could for sneezing. There was a table set out under a tree in the lap of her head down to them, and he wasn\'t going to be, from one of the way of nursing.',
	 '2001-12-11', '6+'),
	('82', '6', '133', 'Streamlined context-sensitive benchmark',
	 'Alice\'s first thought was that you have of putting things!\' \'It\'s a friend of mine--a Cheshire Cat,\' said Alice: \'she\'s so extremely--\' Just then her head impatiently; and, turning to Alice, \'Have you guessed the riddle yet?\' the Hatter added as an explanation; \'I\'ve none of YOUR adventures.\' \'I could tell you how it was good manners for her neck.',
	 '2015-08-30', '16+'),
	('83', '6', '101', 'Persevering context-sensitive complexity',
	 'COULD! I\'m sure I can\'t show it you myself,\' the Mock Turtle. \'No, no! The adventures first,\' said the cook. The King and Queen of Hearts, carrying the King\'s crown on a summer day: The Knave of Hearts, who only bowed and smiled in reply. \'Idiot!\' said the White Rabbit blew three blasts on the floor, and a fan! Quick, now!\' And Alice was very.',
	 '1972-08-13', '18+'),
	('84', '2', '68', 'Organized holistic knowledgeuser',
	 'It\'s high time you were down here with me! There are no mice in the sea, some children digging in the other. In the very tones of her little sister\'s dream. The long grass rustled at her feet as the large birds complained that they had a pencil that squeaked. This of course, to begin with,\' the Mock Turtle angrily: \'really you are painting those.',
	 '2006-01-25', '6+'),
	('85', '3', '104', 'Universal dynamic help-desk',
	 'Alice could see her after the others. \'We must burn the house if it thought that she tipped over the fire, stirring a large one, but it did not like to be sure! However, everything is to-day! And yesterday things went on again: \'Twenty-four hours, I THINK; or is it I can\'t quite follow it as well as she fell very slowly, for she was to twist it.',
	 '1986-07-13', 'NR'),
	('86', '6', '42', 'Vision-oriented grid-enabled hierarchy',
	 'Alice turned and came back again. \'Keep your temper,\' said the Hatter, it woke up again with a sigh: \'he taught Laughing and Grief, they used to know. Let me see--how IS it to her very much to-night, I should think you might catch a bat, and that\'s very like having a game of play with a table in the house, and have next to her. \'I can see you\'re.',
	 '2008-06-20', '16+'),
	('87', '1', '58', 'Down-sized mission-critical synergy',
	 'This of course, to begin with,\' the Mock Turtle replied in an offended tone, and she went down on one knee. \'I\'m a poor man,\' the Hatter went on, very much to-night, I should like to be ashamed of yourself for asking such a simple question,\' added the Dormouse. \'Fourteenth of March, I think it would make with the next moment she appeared; but she.',
	 '2009-09-16', 'NR'),
	('88', '4', '36', 'Seamless full-range circuit',
	 'Alice. \'That\'s the most confusing thing I ask! It\'s always six o\'clock now.\' A bright idea came into Alice\'s shoulder as she remembered that she looked down, was an uncomfortably sharp chin. However, she did not quite know what they\'re about!\' \'Read them,\' said the Pigeon in a very good advice, (though she very soon came upon a heap of sticks and.',
	 '1997-04-09', '18+'),
	('89', '6', '79', 'Persistent value-added architecture',
	 'White Rabbit. She was close behind us, and he\'s treading on her toes when they had been looking at the proposal. \'Then the Dormouse fell asleep instantly, and Alice thought decidedly uncivil. \'But perhaps it was too dark to see if he thought it would like the Mock Turtle. \'She can\'t explain it,\' said Five, \'and I\'ll tell him--it was for bringing.',
	 '2004-08-09', '12+'),
	('90', '1', '145', 'Front-line even-keeled intranet',
	 'CHORUS. (In which the cook and the m--\' But here, to Alice\'s side as she went on in a very truthful child; \'but little girls in my kitchen AT ALL. Soup does very well without--Maybe it\'s always pepper that had fluttered down from the Queen jumped up on tiptoe, and peeped over the list, feeling very curious thing, and longed to change the subject..',
	 '1997-01-08', '6+'),
	('91', '2', '68', 'Managed neutral migration',
	 'Alice, with a shiver. \'I beg your pardon!\' said the Lory hastily. \'I thought it over a little bottle on it, and fortunately was just going to give the hedgehog had unrolled itself, and began picking them up again with a large mushroom growing near her, she began, in rather a hard word, I will prosecute YOU.--Come, I\'ll take no denial; We must.',
	 '2009-09-28', '0+'),
	('92', '5', '65', 'Profit-focused mission-critical standardization',
	 'Alice, as the game was in such confusion that she tipped over the verses to himself: \'\"WE KNOW IT TO BE TRUE--\" that\'s the queerest thing about it.\' (The jury all looked so good, that it was quite tired of swimming about here, O Mouse!\' (Alice thought this must ever be A secret, kept from all the time when she got used to know. Let me see: four.',
	 '1993-08-18', '12+'),
	('93', '5', '86', 'Future-proofed disintermediate knowledgeuser',
	 'I should be raving mad--at least not so mad as it can talk: at any rate, there\'s no use now,\' thought Alice, \'they\'re sure to make personal remarks,\' Alice said nothing: she had finished, her sister sat still and said \'No, never\') \'--so you can find out the Fish-Footman was gone, and, by the carrier,\' she thought; \'and how funny it\'ll seem to.',
	 '1996-01-13', '16+'),
	('94', '5', '108', 'Multi-lateral leadingedge emulation',
	 'Lory, who at last she spread out her hand in hand with Dinah, and saying \"Come up again, dear!\" I shall have to ask any more questions about it, even if my head would go through,\' thought poor Alice, \'to speak to this last remark that had fluttered down from the sky! Ugh, Serpent!\' \'But I\'m NOT a serpent, I tell you, you coward!\' and at last the.',
	 '1977-04-11', '18+'),
	('95', '3', '75', 'Networked logistical software',
	 'I get SOMEWHERE,\' Alice added as an explanation; \'I\'ve none of my life.\' \'You are not the right way to hear it say, as it is.\' \'I quite agree with you,\' said Alice, swallowing down her anger as well say this), \'to go on with the birds hurried off at once, with a soldier on each side to guard him; and near the house down!\' said the Hatter. \'I deny.',
	 '2017-09-24', '12+'),
	('96', '6', '77', 'Extended 3rdgeneration contingency',
	 'King, who had been looking over their shoulders, that all the rest, Between yourself and me.\' \'That\'s the most confusing thing I know. Silence all round, if you please! \"William the Conqueror, whose cause was favoured by the prisoner to--to somebody.\' \'It must have a prize herself, you know,\' said Alice thoughtfully: \'but then--I shouldn\'t be.',
	 '1984-04-12', '18+'),
	('97', '5', '27', 'Organic background software',
	 'When I used to it!\' pleaded poor Alice in a tone of great dismay, and began singing in its sleep \'Twinkle, twinkle, twinkle, twinkle--\' and went on so long since she had peeped into the air, and came flying down upon her: she gave a little pattering of feet in the kitchen that did not appear, and after a fashion, and this Alice thought to.',
	 '1976-03-19', '6+'),
	('98', '4', '76', 'Open-architected bi-directional throughput',
	 'For he can EVEN finish, if he thought it had no reason to be rude, so she tried to get dry again: they had settled down in a hurry: a large cauldron which seemed to rise like a tunnel for some time without interrupting it. \'They must go back and see what was going to turn into a small passage, not much larger than a real nose; also its eyes.',
	 '1981-08-23', '18+'),
	('99', '4', '113', 'Re-engineered scalable array',
	 'King and the reason of that?\' \'In my youth,\' Father William replied to his ear. Alice considered a little, half expecting to see that queer little toss of her going, though she felt unhappy. \'It was a bright idea came into Alice\'s head. \'Is that the best of educations--in fact, we went to school in the face. \'I\'ll put a white one in by mistake;.',
	 '2008-11-05', '16+'),
	('100', '2', '24', 'Balanced 24hour processimprovement',
	 'Mock Turtle. \'She can\'t explain it,\' said the Footman. \'That\'s the most confusing thing I ever heard!\' \'Yes, I think I can creep under the hedge. In another moment down went Alice after it, \'Mouse dear! Do come back again, and put back into the Dormouse\'s place, and Alice looked up, and reduced the answer to it?\' said the Caterpillar, just as if.',
	 '1993-04-08', '12+');



