USE movielista;

-- ----------------------------------- GENERAL INFO

INSERT INTO companies
	(company)
VALUES
	('CGV'),
	('Channel A'),
	('Dramacube'),
	('Dramax'),
	('E Channel'),
	('EBS'),
	('JTBC'),
	('KBS'),
	('MBC'),
	('MBN'),
	('Mnet'),
	('Naver TV Cast'),
	('Netflix'),
	('OCN'),
	('SBS'),
	('SBS SPlus'),
	('Super Action'),
	('Tooniverse'),
	('TV Chosun'),
	('tvN'),
	('Viki');

INSERT INTO countries -- 6
	(country)
VALUES
	('Китай'),
	('Республика Корея'),
	('Таиланд'),
	('Тайвань (Китай)'),
	('Гонконг'),
	('Япония');

INSERT INTO genres
	(genre)
VALUES
	('Комедия'),
	('Фантастика'),
	('Ужасы'),
	('Мелодрама'),
	('Боевик'),
	('Триллер'),
	('Драма'),
	('Мистика'),
	('Детектив'),
	('Приключения'),
	('Фэнтези'),
	('Байопик'),
	('Документальный фильм');

INSERT INTO images -- 150
VALUES
	('1', 'maxime', 'http://purdymarvin.net/'),
	('2', 'quis', 'http://www.turner.org/'),
	('3', 'est', 'http://strosinblanda.com/'),
	('4', 'suscipit', 'http://collinswalter.com/'),
	('5', 'velit', 'http://aufderhar.com/'),
	('6', 'vel', 'http://kunde.biz/'),
	('7', 'et', 'http://www.harris.com/'),
	('8', 'saepe', 'http://www.dooley.com/'),
	('9', 'tempora', 'http://schmitt.info/'),
	('10', 'exercitationem', 'http://moenfeil.org/'),
	('11', 'id', 'http://www.durgan.net/'),
	('12', 'qui', 'http://effertzroberts.com/'),
	('13', 'libero', 'http://www.steuberrohan.org/'),
	('14', 'reiciendis', 'http://barton.org/'),
	('15', 'officia', 'http://www.glover.org/'),
	('16', 'nihil', 'http://www.hamill.com/'),
	('17', 'ex', 'http://douglas.com/'),
	('18', 'ad', 'http://www.murray.biz/'),
	('19', 'voluptatem', 'http://www.aufderhar.com/'),
	('20', 'deleniti', 'http://www.kleinbradtke.com/'),
	('21', 'incidunt', 'http://www.pfeffercarter.com/'),
	('22', 'ab', 'http://bogan.net/'),
	('23', 'eaque', 'http://baumbach.com/'),
	('24', 'a', 'http://www.rodriguezbashirian.com/'),
	('25', 'ut', 'http://www.rowe.com/'),
	('26', 'ducimus', 'http://jenkins.com/'),
	('27', 'fugit', 'http://schoen.com/'),
	('28', 'porro', 'http://steuber.info/'),
	('29', 'sunt', 'http://adams.org/'),
	('30', 'alias', 'http://sauer.com/'),
	('31', 'laborum', 'http://www.okonoberbrunner.com/'),
	('32', 'aliquid', 'http://www.metz.biz/'),
	('33', 'nulla', 'http://www.huel.com/'),
	('34', 'rerum', 'http://www.lehner.com/'),
	('35', 'omnis', 'http://altenwerth.com/'),
	('36', 'ea', 'http://www.barrows.com/'),
	('37', 'iste', 'http://hagenes.com/'),
	('38', 'dolores', 'http://nolan.com/'),
	('39', 'quia', 'http://kertzmann.biz/'),
	('40', 'esse', 'http://dooleyward.biz/'),
	('41', 'ipsa', 'http://www.homenick.com/'),
	('42', 'minus', 'http://www.keeling.com/'),
	('43', 'impedit', 'http://www.breitenberggusikowski.com/'),
	('44', 'voluptas', 'http://gradylueilwitz.com/'),
	('45', 'repellat', 'http://www.crona.com/'),
	('46', 'sed', 'http://klein.com/'),
	('47', 'minima', 'http://wilkinson.org/'),
	('48', 'excepturi', 'http://breitenberg.com/'),
	('49', 'molestiae', 'http://www.ferrycasper.com/'),
	('50', 'aliquam', 'http://harber.net/'),
	('51', 'perspiciatis', 'http://www.durganboyer.com/'),
	('52', 'unde', 'http://hudsonbarrows.biz/'),
	('53', 'expedita', 'http://www.rice.com/'),
	('54', 'necessitatibus', 'http://www.kuvalis.info/'),
	('55', 'quo', 'http://www.volkman.org/'),
	('56', 'quas', 'http://www.mantekuvalis.com/'),
	('57', 'doloremque', 'http://schaefer.biz/'),
	('58', 'veritatis', 'http://ward.org/'),
	('59', 'tenetur', 'http://kuphalgerhold.com/'),
	('60', 'vero', 'http://nicolasharber.com/'),
	('61', 'earum', 'http://predovicparisian.com/'),
	('62', 'pariatur', 'http://www.bode.org/'),
	('63', 'repellendus', 'http://veumorn.com/'),
	('64', 'aut', 'http://www.halvorsoneichmann.org/'),
	('65', 'nobis', 'http://pollich.info/'),
	('66', 'quam', 'http://www.herzog.com/'),
	('67', 'fuga', 'http://botsfordchristiansen.info/'),
	('68', 'non', 'http://stark.com/'),
	('69', 'itaque', 'http://ritchie.com/'),
	('70', 'provident', 'http://emmerich.com/'),
	('71', 'sit', 'http://www.wilkinson.com/'),
	('72', 'hic', 'http://www.fayhilpert.com/'),
	('73', 'enim', 'http://rutherford.com/'),
	('74', 'magni', 'http://www.goyette.com/'),
	('75', 'corrupti', 'http://www.boyle.org/'),
	('76', 'adipisci', 'http://doylejohns.org/'),
	('77', 'quos', 'http://hesselpfannerstill.com/'),
	('78', 'asperiores', 'http://abshirerunolfsdottir.org/'),
	('79', 'aspernatur', 'http://www.pouros.biz/'),
	('80', 'eos', 'http://www.ebert.com/'),
	('81', 'possimus', 'http://www.prohaska.net/'),
	('82', 'harum', 'http://watsica.biz/'),
	('83', 'accusantium', 'http://www.tremblay.com/'),
	('84', 'iusto', 'http://www.ohara.com/'),
	('85', 'autem', 'http://www.wolf.com/'),
	('86', 'blanditiis', 'http://dickinson.org/'),
	('87', 'consequuntur', 'http://kassulke.com/'),
	('88', 'magnam', 'http://lebsack.biz/'),
	('89', 'amet', 'http://www.klocko.com/'),
	('90', 'nam', 'http://prohaska.org/'),
	('91', 'tempore', 'http://homenick.com/'),
	('92', 'voluptatibus', 'http://larson.org/'),
	('93', 'reprehenderit', 'http://langworth.com/'),
	('94', 'deserunt', 'http://www.olson.biz/'),
	('95', 'facere', 'http://www.dibbert.biz/'),
	('96', 'dolorem', 'http://lebsack.com/'),
	('97', 'placeat', 'http://jastfriesen.info/'),
	('98', 'nesciunt', 'http://ruecker.biz/'),
	('99', 'eligendi', 'http://www.sipes.com/'),
	('100', 'cupiditate', 'http://www.hilpertwisoky.com/'),
	('101', 'quod', 'http://westdare.com/'),
	('102', 'similique', 'http://torphy.biz/'),
	('103', 'repudiandae', 'http://orn.com/'),
	('104', 'eius', 'http://wiegandvolkman.com/'),
	('105', 'eveniet', 'http://www.beatty.com/'),
	('106', 'illum', 'http://hermann.com/'),
	('107', 'perferendis', 'http://brakus.net/'),
	('108', 'dignissimos', 'http://purdyyundt.com/'),
	('109', 'quaerat', 'http://www.williamson.com/'),
	('110', 'veniam', 'http://www.ledner.com/'),
	('111', 'delectus', 'http://www.towne.net/'),
	('112', 'mollitia', 'http://www.lang.info/'),
	('113', 'natus', 'http://www.kreiger.com/'),
	('114', 'at', 'http://wymankoch.org/'),
	('115', 'ipsum', 'http://andersonkessler.com/'),
	('116', 'beatae', 'http://www.jacobsonkling.com/'),
	('117', 'numquam', 'http://www.mayert.com/'),
	('118', 'ipsam', 'http://www.rogahn.org/'),
	('119', 'ratione', 'http://www.torp.com/'),
	('120', 'in', 'http://haag.com/'),
	('121', 'culpa', 'http://www.douglas.com/'),
	('122', 'commodi', 'http://gleason.com/'),
	('123', 'dolorum', 'http://www.carrolloconner.com/'),
	('124', 'architecto', 'http://schuster.com/'),
	('125', 'fugiat', 'http://www.stamm.com/'),
	('126', 'assumenda', 'http://greenfelderleuschke.org/'),
	('127', 'sint', 'http://grimes.com/'),
	('128', 'consectetur', 'http://monahan.org/'),
	('129', 'soluta', 'http://gislasonmiller.com/'),
	('130', 'praesentium', 'http://hudsonschamberger.com/'),
	('131', 'recusandae', 'http://www.millerwillms.com/'),
	('132', 'explicabo', 'http://mcculloughrobel.com/'),
	('133', 'atque', 'http://andersonspencer.com/'),
	('134', 'quidem', 'http://kihnschmitt.com/'),
	('135', 'neque', 'http://labadie.org/'),
	('136', 'accusamus', 'http://www.altenwerthbosco.biz/'),
	('137', 'debitis', 'http://wiegand.net/'),
	('138', 'corporis', 'http://kundewehner.com/'),
	('139', 'laudantium', 'http://www.erdmanbechtelar.com/'),
	('140', 'aperiam', 'http://yost.com/'),
	('141', 'doloribus', 'http://rempel.com/'),
	('142', 'vitae', 'http://www.nitzschebode.biz/'),
	('143', 'consequatur', 'http://www.cummingsullrich.org/'),
	('144', 'totam', 'http://windlerspinka.com/'),
	('145', 'maiores', 'http://hamill.org/'),
	('146', 'dolor', 'http://rennerbrakus.info/'),
	('147', 'laboriosam', 'http://www.grantlubowitz.com/'),
	('148', 'optio', 'http://cruickshank.biz/'),
	('149', 'eum', 'http://www.eichmann.com/'),
	('150', 'inventore', 'http://www.schroeder.com/');

INSERT INTO roles
	(role)
VALUES
	('Исполнительный продюсер'),
	('Продюсер'),
	('Со-продюсер'),
	('Помощник продюсера'),
	('Режиссер'),
	('Режиссер-постановщик'),
	('Ассистент режиссера'),
	('Оператор-постановщик'),
	('Начальник актёрского отдела'),
	('Линейный продюсер'),
	('Сценарист'),
	('Арт-директор'),
	('Дизайнер-технолог'),
	('Режиссер монтажа'),
	('Автор сценария'),
	('Ассистент оператора'),
	('Звукорежиссер'),
	('Композитор'),
	('Художник-постановщик'),
	('Актер/актриса'),
	('VFX');

INSERT INTO title_types -- 6
	(title_type)
VALUES
	('Полнометражный фильм'),
	('Короткометражный фильм'),
	('Анимационный фильм'),
	('Телевизионный фильм'),
	('Сериал'),
	('Мини-сериал');
