USE movielista;

-- ----------------------------------- GENERAL INFO

INSERT INTO companies -- 25
	(company)
VALUES
	('Balistreri, Schulist and Denesik'),
	('Beer-Jast'),
	('Beier-Zieme'),
	('Bins, Thiel and Fritsch'),
	('Crona, Volkman and Cormier'),
	('Dietrich and Sons'),
	('Frami-Schumm'),
	('Huel PLC'),
	('Jenkins, Pfannerstill and Daniel'),
	('Kilback, Sanford and Miller'),
	('Kuhlman, Schumm and O\'Connell'),
	('Kuphal, Wiegand and Schamberger'),
	('Lockman, Kessler and Hirthe'),
	('Lynch Ltd'),
	('Mayert-Hermiston'),
	('Mitchell, Howell and Treutel'),
	('Nitzsche, Labadie and Hayes'),
	('O\'Kon-Leffler'),
	('Padberg-Adams'),
	('Satterfield, Welch and Swift'),
	('Schiller, McGlynn and Cummerata'),
	('Schinner-Hilpert'),
	('Schmeler-Koss'),
	('Towne and Sons'),
	('Weimann, Miller and White');

INSERT INTO countries -- 240
	(country)
VALUES
	('Afghanistan'),
	('Albania'),
	('Algeria'),
	('American Samoa'),
	('Andorra'),
	('Angola'),
	('Anguilla'),
	('Antarctica (the territory South of 60 deg S)'),
	('Antigua and Barbuda'),
	('Argentina'),
	('Armenia'),
	('Aruba'),
	('Australia'),
	('Austria'),
	('Azerbaijan'),
	('Bahamas'),
	('Bahrain'),
	('Bangladesh'),
	('Barbados'),
	('Belarus'),
	('Belgium'),
	('Belize'),
	('Benin'),
	('Bermuda'),
	('Bhutan'),
	('Bolivia'),
	('Bosnia and Herzegovina'),
	('Botswana'),
	('Bouvet Island (Bouvetoya)'),
	('Brazil'),
	('British Indian Ocean Territory (Chagos Archipelago)'),
	('British Virgin Islands'),
	('Brunei Darussalam'),
	('Bulgaria'),
	('Burkina Faso'),
	('Burundi'),
	('Cambodia'),
	('Cameroon'),
	('Canada'),
	('Cape Verde'),
	('Cayman Islands'),
	('Central African Republic'),
	('Chad'),
	('Chile'),
	('China'),
	('Christmas Island'),
	('Cocos (Keeling) Islands'),
	('Colombia'),
	('Comoros'),
	('Congo'),
	('Cook Islands'),
	('Costa Rica'),
	('Cote d\'Ivoire'),
	('Croatia'),
	('Cuba'),
	('Cyprus'),
	('Czech Republic'),
	('Denmark'),
	('Djibouti'),
	('Dominica'),
	('Dominican Republic'),
	('Ecuador'),
	('Egypt'),
	('El Salvador'),
	('Equatorial Guinea'),
	('Eritrea'),
	('Estonia'),
	('Falkland Islands (Malvinas)'),
	('Faroe Islands'),
	('Fiji'),
	('Finland'),
	('France'),
	('French Guiana'),
	('French Polynesia'),
	('French Southern Territories'),
	('Gabon'),
	('Gambia'),
	('Georgia'),
	('Germany'),
	('Ghana'),
	('Gibraltar'),
	('Greece'),
	('Greenland'),
	('Grenada'),
	('Guadeloupe'),
	('Guam'),
	('Guatemala'),
	('Guernsey'),
	('Guinea'),
	('Guinea-Bissau'),
	('Guyana'),
	('Haiti'),
	('Heard Island and McDonald Islands'),
	('Holy See (Vatican City State)'),
	('Honduras'),
	('Hong Kong'),
	('Hungary'),
	('Iceland'),
	('India'),
	('Indonesia'),
	('Iran'),
	('Iraq'),
	('Ireland'),
	('Isle of Man'),
	('Israel'),
	('Italy'),
	('Jamaica'),
	('Japan'),
	('Jersey'),
	('Jordan'),
	('Kazakhstan'),
	('Kenya'),
	('Kiribati'),
	('Korea'),
	('Kuwait'),
	('Kyrgyz Republic'),
	('Lao People\'s Democratic Republic'),
	('Latvia'),
	('Lebanon'),
	('Lesotho'),
	('Liberia'),
	('Libyan Arab Jamahiriya'),
	('Liechtenstein'),
	('Lithuania'),
	('Luxembourg'),
	('Macao'),
	('Macedonia'),
	('Madagascar'),
	('Malaysia'),
	('Maldives'),
	('Mali'),
	('Malta'),
	('Marshall Islands'),
	('Martinique'),
	('Mauritania'),
	('Mauritius'),
	('Mayotte'),
	('Mexico'),
	('Micronesia'),
	('Moldova'),
	('Monaco'),
	('Mongolia'),
	('Montenegro'),
	('Montserrat'),
	('Morocco'),
	('Mozambique'),
	('Myanmar'),
	('Namibia'),
	('Nauru'),
	('Nepal'),
	('Netherlands'),
	('Netherlands Antilles'),
	('New Caledonia'),
	('New Zealand'),
	('Nicaragua'),
	('Niger'),
	('Nigeria'),
	('Niue'),
	('Norfolk Island'),
	('Northern Mariana Islands'),
	('Norway'),
	('Oman'),
	('Pakistan'),
	('Palau'),
	('Palestinian Territory'),
	('Panama'),
	('Papua New Guinea'),
	('Paraguay'),
	('Peru'),
	('Philippines'),
	('Pitcairn Islands'),
	('Poland'),
	('Portugal'),
	('Puerto Rico'),
	('Qatar'),
	('Reunion'),
	('Romania'),
	('Russian Federation'),
	('Rwanda'),
	('Saint Barthelemy'),
	('Saint Helena'),
	('Saint Kitts and Nevis'),
	('Saint Lucia'),
	('Saint Martin'),
	('Saint Pierre and Miquelon'),
	('Saint Vincent and the Grenadines'),
	('Samoa'),
	('San Marino'),
	('Sao Tome and Principe'),
	('Saudi Arabia'),
	('Senegal'),
	('Serbia'),
	('Seychelles'),
	('Sierra Leone'),
	('Singapore'),
	('Slovakia (Slovak Republic)'),
	('Slovenia'),
	('Solomon Islands'),
	('South Africa'),
	('South Georgia and the South Sandwich Islands'),
	('Spain'),
	('Sri Lanka'),
	('Sudan'),
	('Suriname'),
	('Svalbard & Jan Mayen Islands'),
	('Swaziland'),
	('Sweden'),
	('Switzerland'),
	('Syrian Arab Republic'),
	('Taiwan'),
	('Tajikistan'),
	('Tanzania'),
	('Thailand'),
	('Timor-Leste'),
	('Togo'),
	('Tokelau'),
	('Tonga'),
	('Trinidad and Tobago'),
	('Tunisia'),
	('Turkey'),
	('Turkmenistan'),
	('Turks and Caicos Islands'),
	('Tuvalu'),
	('Uganda'),
	('Ukraine'),
	('United Arab Emirates'),
	('United Kingdom'),
	('United States Minor Outlying Islands'),
	('United States of America'),
	('United States Virgin Islands'),
	('Uruguay'),
	('Uzbekistan'),
	('Vanuatu'),
	('Venezuela'),
	('Vietnam'),
	('Wallis and Futuna'),
	('Western Sahara'),
	('Yemen'),
	('Zambia'),
	('Zimbabwe');

INSERT INTO genres -- 22
	(genre)
VALUES
	('Action'),
	('Adventure'),
	('Animation'),
	('Biography'),
	('Comedy'),
	('Crime'),
	('Documentary'),
	('Drama'),
	('Family'),
	('Fantasy'),
	('Film Noir'),
	('History'),
	('Horror'),
	('Music'),
	('Musical'),
	('Mystery'),
	('Romance'),
	('Sci-Fi'),
	('Sport'),
	('Superhero'),
	('Thriller'),
	('Western');

INSERT INTO images -- 150
VALUES
	('1', 'velit', 'http://lorempixel.com/1/1/abstract/'),
	('2', 'reprehenderit', 'http://lorempixel.com/1/1/abstract/'),
	('3', 'quisquam', 'http://lorempixel.com/1/1/abstract/'),
	('4', 'veritatis', 'http://lorempixel.com/1/1/abstract/'),
	('5', 'deserunt', 'http://lorempixel.com/1/1/abstract/'),
	('6', 'qui', 'http://lorempixel.com/1/1/abstract/'),
	('7', 'aut', 'http://lorempixel.com/1/1/abstract/'),
	('8', 'et', 'http://lorempixel.com/1/1/abstract/'),
	('9', 'quo', 'http://lorempixel.com/1/1/abstract/'),
	('10', 'tenetur', 'http://lorempixel.com/1/1/abstract/'),
	('11', 'repellendus', 'http://lorempixel.com/1/1/abstract/'),
	('12', 'deserunt', 'http://lorempixel.com/1/1/abstract/'),
	('13', 'velit', 'http://lorempixel.com/1/1/abstract/'),
	('14', 'aut', 'http://lorempixel.com/1/1/abstract/'),
	('15', 'ipsa', 'http://lorempixel.com/1/1/abstract/'),
	('16', 'fugiat', 'http://lorempixel.com/1/1/abstract/'),
	('17', 'suscipit', 'http://lorempixel.com/1/1/abstract/'),
	('18', 'vero', 'http://lorempixel.com/1/1/abstract/'),
	('19', 'rerum', 'http://lorempixel.com/1/1/abstract/'),
	('20', 'iure', 'http://lorempixel.com/1/1/abstract/'),
	('21', 'unde', 'http://lorempixel.com/1/1/abstract/'),
	('22', 'nemo', 'http://lorempixel.com/1/1/abstract/'),
	('23', 'deleniti', 'http://lorempixel.com/1/1/abstract/'),
	('24', 'qui', 'http://lorempixel.com/1/1/abstract/'),
	('25', 'molestiae', 'http://lorempixel.com/1/1/abstract/'),
	('26', 'omnis', 'http://lorempixel.com/1/1/abstract/'),
	('27', 'est', 'http://lorempixel.com/1/1/abstract/'),
	('28', 'sint', 'http://lorempixel.com/1/1/abstract/'),
	('29', 'debitis', 'http://lorempixel.com/1/1/abstract/'),
	('30', 'sed', 'http://lorempixel.com/1/1/abstract/'),
	('31', 'ipsa', 'http://lorempixel.com/1/1/abstract/'),
	('32', 'odit', 'http://lorempixel.com/1/1/abstract/'),
	('33', 'sit', 'http://lorempixel.com/1/1/abstract/'),
	('34', 'tenetur', 'http://lorempixel.com/1/1/abstract/'),
	('35', 'nemo', 'http://lorempixel.com/1/1/abstract/'),
	('36', 'dolor', 'http://lorempixel.com/1/1/abstract/'),
	('37', 'unde', 'http://lorempixel.com/1/1/abstract/'),
	('38', 'amet', 'http://lorempixel.com/1/1/abstract/'),
	('39', 'eos', 'http://lorempixel.com/1/1/abstract/'),
	('40', 'minus', 'http://lorempixel.com/1/1/abstract/'),
	('41', 'optio', 'http://lorempixel.com/1/1/abstract/'),
	('42', 'perspiciatis', 'http://lorempixel.com/1/1/abstract/'),
	('43', 'velit', 'http://lorempixel.com/1/1/abstract/'),
	('44', 'voluptatem', 'http://lorempixel.com/1/1/abstract/'),
	('45', 'quo', 'http://lorempixel.com/1/1/abstract/'),
	('46', 'eos', 'http://lorempixel.com/1/1/abstract/'),
	('47', 'sed', 'http://lorempixel.com/1/1/abstract/'),
	('48', 'quidem', 'http://lorempixel.com/1/1/abstract/'),
	('49', 'sint', 'http://lorempixel.com/1/1/abstract/'),
	('50', 'fugit', 'http://lorempixel.com/1/1/abstract/'),
	('51', 'accusamus', 'http://lorempixel.com/1/1/abstract/'),
	('52', 'quisquam', 'http://lorempixel.com/1/1/abstract/'),
	('53', 'dolorum', 'http://lorempixel.com/1/1/abstract/'),
	('54', 'tempore', 'http://lorempixel.com/1/1/abstract/'),
	('55', 'qui', 'http://lorempixel.com/1/1/abstract/'),
	('56', 'ut', 'http://lorempixel.com/1/1/abstract/'),
	('57', 'voluptatum', 'http://lorempixel.com/1/1/abstract/'),
	('58', 'placeat', 'http://lorempixel.com/1/1/abstract/'),
	('59', 'illo', 'http://lorempixel.com/1/1/abstract/'),
	('60', 'aspernatur', 'http://lorempixel.com/1/1/abstract/'),
	('61', 'eum', 'http://lorempixel.com/1/1/abstract/'),
	('62', 'et', 'http://lorempixel.com/1/1/abstract/'),
	('63', 'quae', 'http://lorempixel.com/1/1/abstract/'),
	('64', 'est', 'http://lorempixel.com/1/1/abstract/'),
	('65', 'labore', 'http://lorempixel.com/1/1/abstract/'),
	('66', 'consequuntur', 'http://lorempixel.com/1/1/abstract/'),
	('67', 'recusandae', 'http://lorempixel.com/1/1/abstract/'),
	('68', 'explicabo', 'http://lorempixel.com/1/1/abstract/'),
	('69', 'ducimus', 'http://lorempixel.com/1/1/abstract/'),
	('70', 'voluptatem', 'http://lorempixel.com/1/1/abstract/'),
	('71', 'laboriosam', 'http://lorempixel.com/1/1/abstract/'),
	('72', 'numquam', 'http://lorempixel.com/1/1/abstract/'),
	('73', 'aut', 'http://lorempixel.com/1/1/abstract/'),
	('74', 'possimus', 'http://lorempixel.com/1/1/abstract/'),
	('75', 'molestiae', 'http://lorempixel.com/1/1/abstract/'),
	('76', 'debitis', 'http://lorempixel.com/1/1/abstract/'),
	('77', 'tempora', 'http://lorempixel.com/1/1/abstract/'),
	('78', 'quos', 'http://lorempixel.com/1/1/abstract/'),
	('79', 'voluptate', 'http://lorempixel.com/1/1/abstract/'),
	('80', 'temporibus', 'http://lorempixel.com/1/1/abstract/'),
	('81', 'veniam', 'http://lorempixel.com/1/1/abstract/'),
	('82', 'rerum', 'http://lorempixel.com/1/1/abstract/'),
	('83', 'quasi', 'http://lorempixel.com/1/1/abstract/'),
	('84', 'impedit', 'http://lorempixel.com/1/1/abstract/'),
	('85', 'ipsum', 'http://lorempixel.com/1/1/abstract/'),
	('86', 'eligendi', 'http://lorempixel.com/1/1/abstract/'),
	('87', 'consequuntur', 'http://lorempixel.com/1/1/abstract/'),
	('88', 'nam', 'http://lorempixel.com/1/1/abstract/'),
	('89', 'animi', 'http://lorempixel.com/1/1/abstract/'),
	('90', 'et', 'http://lorempixel.com/1/1/abstract/'),
	('91', 'et', 'http://lorempixel.com/1/1/abstract/'),
	('92', 'optio', 'http://lorempixel.com/1/1/abstract/'),
	('93', 'incidunt', 'http://lorempixel.com/1/1/abstract/'),
	('94', 'quisquam', 'http://lorempixel.com/1/1/abstract/'),
	('95', 'nobis', 'http://lorempixel.com/1/1/abstract/'),
	('96', 'tenetur', 'http://lorempixel.com/1/1/abstract/'),
	('97', 'sint', 'http://lorempixel.com/1/1/abstract/'),
	('98', 'fugit', 'http://lorempixel.com/1/1/abstract/'),
	('99', 'nam', 'http://lorempixel.com/1/1/abstract/'),
	('100', 'qui', 'http://lorempixel.com/1/1/abstract/'),
	('101', 'amet', 'http://lorempixel.com/1/1/abstract/'),
	('102', 'autem', 'http://lorempixel.com/1/1/abstract/'),
	('103', 'voluptate', 'http://lorempixel.com/1/1/abstract/'),
	('104', 'quaerat', 'http://lorempixel.com/1/1/abstract/'),
	('105', 'ea', 'http://lorempixel.com/1/1/abstract/'),
	('106', 'distinctio', 'http://lorempixel.com/1/1/abstract/'),
	('107', 'quo', 'http://lorempixel.com/1/1/abstract/'),
	('108', 'laudantium', 'http://lorempixel.com/1/1/abstract/'),
	('109', 'non', 'http://lorempixel.com/1/1/abstract/'),
	('110', 'laborum', 'http://lorempixel.com/1/1/abstract/'),
	('111', 'dicta', 'http://lorempixel.com/1/1/abstract/'),
	('112', 'incidunt', 'http://lorempixel.com/1/1/abstract/'),
	('113', 'sint', 'http://lorempixel.com/1/1/abstract/'),
	('114', 'odio', 'http://lorempixel.com/1/1/abstract/'),
	('115', 'officiis', 'http://lorempixel.com/1/1/abstract/'),
	('116', 'consequatur', 'http://lorempixel.com/1/1/abstract/'),
	('117', 'voluptas', 'http://lorempixel.com/1/1/abstract/'),
	('118', 'libero', 'http://lorempixel.com/1/1/abstract/'),
	('119', 'nihil', 'http://lorempixel.com/1/1/abstract/'),
	('120', 'laboriosam', 'http://lorempixel.com/1/1/abstract/'),
	('121', 'ut', 'http://lorempixel.com/1/1/abstract/'),
	('122', 'voluptatibus', 'http://lorempixel.com/1/1/abstract/'),
	('123', 'consequatur', 'http://lorempixel.com/1/1/abstract/'),
	('124', 'dolorem', 'http://lorempixel.com/1/1/abstract/'),
	('125', 'cum', 'http://lorempixel.com/1/1/abstract/'),
	('126', 'dolore', 'http://lorempixel.com/1/1/abstract/'),
	('127', 'magnam', 'http://lorempixel.com/1/1/abstract/'),
	('128', 'est', 'http://lorempixel.com/1/1/abstract/'),
	('129', 'voluptatem', 'http://lorempixel.com/1/1/abstract/'),
	('130', 'beatae', 'http://lorempixel.com/1/1/abstract/'),
	('131', 'est', 'http://lorempixel.com/1/1/abstract/'),
	('132', 'voluptatem', 'http://lorempixel.com/1/1/abstract/'),
	('133', 'quia', 'http://lorempixel.com/1/1/abstract/'),
	('134', 'temporibus', 'http://lorempixel.com/1/1/abstract/'),
	('135', 'fugit', 'http://lorempixel.com/1/1/abstract/'),
	('136', 'aut', 'http://lorempixel.com/1/1/abstract/'),
	('137', 'et', 'http://lorempixel.com/1/1/abstract/'),
	('138', 'dicta', 'http://lorempixel.com/1/1/abstract/'),
	('139', 'maiores', 'http://lorempixel.com/1/1/abstract/'),
	('140', 'neque', 'http://lorempixel.com/1/1/abstract/'),
	('141', 'ut', 'http://lorempixel.com/1/1/abstract/'),
	('142', 'ab', 'http://lorempixel.com/1/1/abstract/'),
	('143', 'esse', 'http://lorempixel.com/1/1/abstract/'),
	('144', 'eum', 'http://lorempixel.com/1/1/abstract/'),
	('145', 'voluptates', 'http://lorempixel.com/1/1/abstract/'),
	('146', 'molestias', 'http://lorempixel.com/1/1/abstract/'),
	('147', 'in', 'http://lorempixel.com/1/1/abstract/'),
	('148', 'aut', 'http://lorempixel.com/1/1/abstract/'),
	('149', 'et', 'http://lorempixel.com/1/1/abstract/'),
	('150', 'iste', 'http://lorempixel.com/1/1/abstract/');

INSERT INTO roles
	(role)
VALUES
	('Executive producer'),
	('Producer'),
	('Director'),
	('Writer'),
	('Star'),
	('Director of photography'),
	('Film editor'),
	('Casting '),
	('Production Design'),
	('Music'),
	('Art Direction'),
	('Set Decoration'),
	('Assistant Director'),
	('Special Effects'),
	('Visual Effects'),
	('Sound designer'),
	('Stunt');

INSERT INTO title_types -- 6
	(title_type)
VALUES
	('Feature Film'),
	('TV Movie'),
	('TV Series'),
	('Short Film'),
	('Mini-Series'),
	('Animation');
